apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Flag_deployement
on:
  push:
    branches:
      - master
jobs:
  Build:
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: Checkout
        uses: cloudbees-io/checkout@v1
      
      - uses: docker://maven:3-eclipse-temurin-17
        name: Build
        kind: build
        run: |
         mvn spring-javaformat:apply
         mvn clean package
        shell: sh

      - name: Verify Dockerfile location
        uses: docker://maven:3-eclipse-temurin-17
        run: ls -al ./
      
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ secrets.dockerurl }}
          username: ${{ secrets.dockerusername }}
          password: ${{ secrets.dockerpasswd }}
          
      - name: Push image to OCI registry
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.dockerurl }}/${{ secrets.dockerusername }}/petclinic:3.2.4

  Deploy:
    needs: Build
    environment: production
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: cashokannamalai/kubeconfig@v1
        name: Set kubeconfig
        with:
          secname: ${{ secrets.kubeconfig }}
      - uses: cloudbees-io/kustomize-deploy@v1
        name: deploy
        kind: deploy
        with:
          kustomization-base-dir: ${{ cloudbees.workspace }}/base
          